#!/web/wikiotics.org/deployenv/bin/python

# Set up path
import sys
sys.path.append("/web/wikiotics.org/ductus")
sys.path.append("/web/wikiotics.org/python-include")

# Initialize Django
import ductus.settings
from django.core.management import setup_environ
setup_environ(ductus.settings)

# Actual script
import toml, json
from collections import OrderedDict
from django.contrib.auth.models import User
from ductus.wiki.models import WikiRevision

output = []
for user in User.objects.all():
    d = OrderedDict()
    d['username'] = user.username
    #if user.email:
    #    d['email'] = user.email
    contributions = WikiRevision.objects.filter(author=user).order_by('timestamp')
    cnt = contributions.count()
    if cnt > 0:
        d['contributions'] = cnt
        d['first_contribution'] = contributions[0].timestamp
        d['final_contribution'] = contributions.reverse()[0].timestamp
    output.append(d)
output.sort(reverse=True, key=lambda x: x.get('contributions', 0))
print toml.dumps({'users': output})
